### ISSUE TITLE
Kernel Config

### ISSUE THREAD

**Issue by North-West-Wind** [gma/pop-os-kernel-builder#1]
This script is great to build a kernel on pop, but is it possible to change the config of the kernel source?

**Comment by gma** [comment]
It doesn't support it in any automated way, but you all you need to do is to get the script to pause so you can `cd` into the kernel source folder and run the commands you want to use to configure the kernel. It's a long time since I've needed to, but I recall that it used to be possible to copy a file into the source tree that contained all the answers to your config questions.

So maybe after you've done it once manually, that'd be a good way to do it.

To get the script to pause while I did some config (e.g. by running `make menuconfig`) I'd probably just throw in something like this:

```sh
read -p "Configure the kernel in $CHROOT/$KERNEL_SRC, then press enter"
```

You could add that just after the call to the `apply_patches` function near the bottom of the script.

I've not tried custom config on a modern Ubuntu based distro, so I'm not sure whether `make menuconfig` would be enough. It's where I'd start, but this might also be relevant:

https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel#Modifying_the_configuration

**Comment by North-West-Wind** [comment]
Alright thanks
